name: Check links

on:
  # Allow people to trigger the workflow manually.
  # Reference: https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  workflow_dispatch: {}

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # Initially copied from: https://github.com/microbiomedata/docs/blob/30b3adcf15cea6286a92d1a1712b822b3b5c8f06/.github/workflows/check-links-and-spelling.yml#L29-L39
    # Reference: https://github.com/gaurav-nelson/github-action-markdown-link-check
    - name: Check links  # was: Run Markdown Link Check
      uses: gaurav-nelson/github-action-markdown-link-check@v1 # Source: https://github.com/tcort/markdown-link-check
      id: linkcheck
      continue-on-error: true
      with:
        use-verbose-mode: 'yes'
        file-extension: '.md'
        base-branch: 'main'

    - name: Do something with the link checker output
      run: |
        echo "--- A ---"
        echo ${{ steps.linkcheck.outputs }}
        echo "--- B ---"
        echo ${{ steps.linkcheck.outputs.* }}
